import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/sections/Footer";

// const inter = Inter({ subsets: ["latin"] });
const avant = localFont({ src: "fonts/ITCAvantGardePro-Md.ttf" });
// const avant = localFont({ src: "" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={avant.className}>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
